# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb2118f75e4879706ae166abe9deada8ddf45114851f69f6b62afdcc3e5e27bb42c05143a77e9c655a1960b13952529024fd816a50f50e30dde5283490f8f04e

test:
  secret_key_base: fbd752cef483f5733c349cf738f248158d45bcce5a704162a89496791fa9ec8a1e498aea59e61e58d4629072f11b29c3e3083b885b7d02b9f130d95cc6b4a02c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
